### ISSUE TITLE
Can't use together with @apply

### ISSUE THREAD

**Issue by mainrs** [jonaskay/tailwindcss-elevation#148]
Hi!

I am using this together with NuxtJS but I can't get it to work with the `@apply` directive. It works when specifying the class directly on the element though. I've added the plugin as described in the readme.

**Comment by jonaskay** [comment]
Are you able to use other Tailwind classes with the `@apply` directive? Do they work fine? 

If they are working fine, is it possible for you to share your CSS file where you use the `@apply` directive?

**Comment by jonaskay** [comment]
I'm closing this since I can't investigate the issue further without more details.
