### ISSUE TITLE
Update dependencies to use tailwind v3.0

### ISSUE THREAD

**Issue by nickt26** [jonaskay/tailwindcss-elevation#223]

**Comment by evdama** [comment]
any news on this? 😃

**Comment by jonaskay** [comment]
Sorry for the late answer. I will be doing some bigger updates during this summer and this update is a high priority.

**Comment by hillin** [comment]
Would expect this too, it works well with tailwindcss 3.x, it's just a little bit annoying everytime we run yarn, it complains
> tailwindcss-elevation@1.0.1" has incorrect peer dependency "tailwindcss@^2.0.1".

**Comment by zaclimon** [comment]
Is there any news? I know that we could still bypass the issue by using the `--legacy-peer-deps` option, but installing 2 versions of tailwind is not the best solution.

Perhaps as a stopgap measure, the plugin could be updated for Tailwind 3 and then if there are some bigger features in the roadmap, then they could follow suit. What do you think @jonaskay?

**Comment by jonaskay** [comment]
Hi! I'm very late with this but a new version is out: https://github.com/jonaskay/tailwindcss-elevation/releases/tag/v2.0.0

Please note that this update introduces breaking changes to how options are passed to the plugin. You will find new instructions in the README. Basically the plugin is now following the current Tailwind CSS instructions for passing options to plugins.

@zaclimon thank you for your suggestion! I have postponed bigger changes to get this update out.
