### ISSUE TITLE
different colors per elevation

### ISSUE THREAD

**Issue by evdama** [jonaskay/tailwindcss-elevation#5]
it would be great for theming to have the option for different colors with each `elevation-<z>`. For example, if I have two buttons side by side and one should have the default gray shadow and the other one a blue-500, how would I do that today?

**Comment by jonaskay** [comment]
Having a different CSS class for each color variant would add a lot of extra code to the outputted CSS file. Therefore, I'm hesitant to include this as a config option.

You can change the box-shadow color outside the box-shadow property with this https://stackoverflow.com/a/10989662. 

However, tailwindcss-elevation uses black as the default color; it doesn't omit color from `box-shadow`. This means that you can't actually use `color` property as box-shadow color. Maybe users should have the option to leave color out from the generated box-shadow properties.

I'll leave this issue open for now to see if there are other opinions out there.

**Comment by jonaskay** [comment]
I’m closing this issue because it has been inactive for almost two months.

**Comment by jigneshsuvariya** [comment]
How to use Dark mode as default black will not help over there.
